name: Spirits
version: MYSTIC-1.0.13.1
main: me.numin.spirits.Spirits
api-version: 1.13
softdepend: [ProjectKorra]
authors: [Numin]
description: Enables your players to be Spirits.

permissions:
  bending.spirit:
    default: true
    description: Grants access to all Spirit abilities.
    children:
      bending.command.choose.spirit: true
      bending.ability.agility: true
      bending.ability.phase: true
      bending.ability.possess: true
      bending.ability.vanish: true
  bending.lightspirit:
    default: true
    description: Grants access to all LightSpirit abilities.
    children:
      bending.command.choose.lightspirit: true
      bending.ability.alleviate: true
      bending.ability.orb: true
      bending.ability.rejuvenate: true
      bending.ability.shelter: true
      bending.ability.lightblast: true
  bending.darkspirit:
    default: true
    description: Grants access to all DarkSpirit abilities.
    children:
      bending.command.choose.darkspirit: true
      bending.ability.infest: true
      bending.ability.intoxicate: true
      bending.ability.shackle: true
      bending.ability.strike: true